development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>

test:
  adapter: test
  #adapter: redis
  #url: <%= ENV.fetch("REDIS_URL") %>

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
